### Site info:
title: csxiaofei's blog
tagline: Six years later, it will be 2021, and I will be 30.
author: csxiaofei
email: bzhnja@gmail.com
description: "This is just csxiaofei's blog." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "computer science, programming, travelling, on the way"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bzhnja.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: GeSpontaneously
github_username:  bzhnja
disqus_shortname: csxiaofei
favicon:     "/images/cs.ico"
aboutme: Hi, this is csxiaofei. "cs" is the abbreviation of Computer Science, and "xiaofei" is my nickname. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/me.jpeg" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Freshman21
      href: http://yulijia.net/freshman21
      title: Another Jekyll blog theme
    - name: author's website
      href: http://yulijia.net/
      title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
